# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"


[[redirects]]
  from = "/api/slack/*"
  to = "/.netlify/functions/slack-:splat"
  status = 200
